{% set name = "dmgbuild" %}
{% set version = "1.6.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 508689a0e15ac45e554f73133b6aeaf6e36d800beaa7003c935f3fbd5cfb21af

build:
  number: 0
  skip: true  # [py<310]
  skip: true  # [not osx]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - dmgbuild = dmgbuild.__main__:main

requirements:
  host:
    - python
    - pip
    - setuptools 80.9.0
  run:
    - python
    - importlib_resources >=5.9
    - ds_store >=1.1.0
    - mac_alias >=2.0.1
  run_constrained:
    - pyobjc-framework-Quartz >=3.0.4

test:
  imports:
    - dmgbuild
  requires:
    - pip
    - pytest
    - python
  source_files:
    - tests
  commands:
    - pip check
    - pytest -vvv

about:
  home: https://github.com/dmgbuild/dmgbuild
  doc_url: https://dmgbuild.readthedocs.io/en/latest/
  dev_url: https://github.com/dmgbuild/dmgbuild
  summary: macOS command line utility to build disk images
  description: |
    dmgbuild is a command line tool to create macOS disk images (aka .dmg files). 
    dmgbuild allows for full customization of the resulting disk image, without relying on Finder,
    and without using deprecated APIs (like the Alias Manager functions).
    dmgbuild is a wrapper around macOS specific tools, so it can't be used on Windows or Linux.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotduarte
